// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID      uuid.UUID `json:"id"`
	Userid  uuid.UUID `json:"userid"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Date    time.Time `json:"date"`
}

type Medium struct {
	ID     uuid.UUID `json:"id"`
	Blogid uuid.UUID `json:"blogid"`
	Path   string    `json:"path"`
	Source string    `json:"source"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
	Date   time.Time `json:"date"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Email     string    `json:"email"`
	Isadmin   bool      `json:"isadmin"`
	Createdat time.Time `json:"createdat"`
}
