CREATE TABLE users (
   id UUID PRIMARY KEY NOT NULL,
   firstName VARCHAR(100) NOT NULL,
   lastName VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
