CREATE TABLE users (
   id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
   firstName VARCHAR(100) NOT NULL,
   lastName VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   isAdmin BOOLEAN NOT NULL DEFAULT FALSE,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
