CREATE TABLE media (
   id UUID PRIMARY KEY NOT NULL,
   blogIdd UUID NOT NULL,
   path VARCHAR(255) NOT NULL,
   source VARCHAR(100) NOT NULL,
   name VARCHAR(255) NOT NULL,
   type VARCHAR(50) NOT NULL,
   date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_blog_id ON media (blogIdd);
